# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reservation' do
 pod 'Alamofire', '~> 4.4'
 pod 'RxSwift', '4.3.1'
 pod 'RxCocoa', '4.3.1'
 pod 'RxDataSources', '3.0.0'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'Kingfisher' ,  '~> 5.0'
 pod 'SnapKit', '~> 5.0.0'
end

target 'ReservationTests' do
  pod  'RxBlocking' ,  '4.3.1'
  pod  'RxTest' ,  '4.3.1'
end
